#  numpy exercises



Run the `initialize.py` module, then for each question you can query the
answer or an hint with `hint(n)` or `answer(n)` for `n` question number.

In [ ]:
%run initialise.py

#### 1. Import the numpy package under the name `np` (★☆☆)

In [1]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [2]:
import platform
print('Python version: ' + platform.python_version())

Python version: 3.11.5


#### 3. Create a null vector of size 10 (★☆☆)

In [3]:
empty = np.zeros(10)
print(empty)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4. How to find the memory size of any array (★☆☆)

In [8]:
print(empty.nbytes)

80


#### 5. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [23]:
arr = np.zeros((10), dtype='int'  )  
print(arr) 
arr[4]=1
print(arr)

[0 0 0 0 0 0 0 0 0 0]
[0 0 0 0 1 0 0 0 0 0]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [28]:
arr = np.arange(10, 50)  
print(arr)
print(type(arr))

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]
<class 'numpy.ndarray'>


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [37]:
arr = np.array((1,2,3,4,5))
print(arr)
arr = np.flip(arr) # flip = reverse
print(arr)

[1 2 3 4 5]
[5 4 3 2 1]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [49]:
arr = (np.arange(0,9).reshape(3,3)) # reshape make matrix
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [87]:
arr=[1,2,0,0,4,0]
for i in arr:
    if(i!=0):
        print(i)
    

1
2
4


#### 11. Create a 3x3 identity matrix (★☆☆)

In [100]:
identity_matrix = np.eye(3)
identity_matrix = identity_matrix.astype(int)
print(identity_matrix)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [52]:
arr = np.random.rand(3,3,3) #(row,)
arr

array([[[0.88828807, 0.75119828, 0.1914554 ],
        [0.05515969, 0.72826198, 0.3057574 ],
        [0.08967598, 0.96903234, 0.8944916 ]],

       [[0.22628908, 0.62471622, 0.3455872 ],
        [0.08842885, 0.01578969, 0.14239244],
        [0.59413263, 0.23025561, 0.6283835 ]],

       [[0.76081512, 0.82140887, 0.14960765],
        [0.25836688, 0.26118689, 0.76588905],
        [0.892856  , 0.44501736, 0.47615758]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [93]:
arr = np.random.rand(10,10)
print(np.max(arr))
print(np.min(arr))

0.9955322360071965
0.003978489174250588


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [95]:
arr = np.random.rand(30)
print(np.mean(arr))

0.5895050026044337


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [179]:
rows = 3
cols = 3
array = np.zeros((rows, cols), dtype=int)
array[0, 0:3] = 1 #first row ..define first row ,column 0:3
array[2,0 :3] = 1   #last row 
array[0:3, 0] = 1    # first column ..define first column 0,row 0:3
array[0:3, 2] = 1 #last column
print(array)

[[1 1 1]
 [1 0 1]
 [1 1 1]]


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [181]:
arr = np.diag([1,2,3,4])
print(arr)

[[1 0 0 0]
 [0 2 0 0]
 [0 0 3 0]
 [0 0 0 4]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [46]:
matrix = np.zeros((8, 8))
for i in range(8): # i :row
    for j in range(8): # j : column
        if (i + j) % 2 == 0:
            matrix[i][j] = 0
        else:
            matrix[i][j] = 1
print(matrix)

[[0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]
 [0. 1. 0. 1. 0. 1. 0. 1.]
 [1. 0. 1. 0. 1. 0. 1. 0.]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? (★☆☆)

In [206]:
array = np.zeros((6, 7, 8)) #(duplicate,row,column)
index = np.unravel_index(100, array.shape) #unravel_index :function converts a flat index to a tuple to the multi-dimensional array shape(x,y,z).
""""x = index // (7 * 8)
y = (index % (7 * 8)) // 8
z = (index % (7 * 8)) % 8"""
print(index)

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [213]:
arr = [0, 1, 2]
print(np.tile(arr, (8,8)))

[[0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]
 [0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2 0 1 2]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [210]:
matrix = np.random.rand(5, 5)
mean = np.mean(matrix)
std = np.std(matrix)
#x*=(x-mean/std)
normalized_matrix = (matrix - mean) / std
print(normalized_matrix)


[[ 1.53747702  0.15836111  0.87808192  0.38494841  1.09161845]
 [-1.41092666  1.36723912 -0.97463529  0.1662164   0.21034233]
 [ 1.2873316   0.16153202 -1.12750698 -1.50935424 -1.6143564 ]
 [-0.22896175  0.09632473  0.21834952  0.6326832  -1.52860652]
 [ 0.37103836 -1.29619275  1.37170569  0.65465943 -0.89736873]]


In [212]:
random_matrix = np.random.rand(5, 5)

normalized_matrix = random_matrix / np.linalg.norm(random_matrix)

# Print the normalized matrix
print(normalized_matrix)

[[0.16779918 0.13153655 0.30720396 0.14498308 0.16751469]
 [0.17637391 0.12457741 0.32329373 0.1083126  0.17245203]
 [0.23303884 0.32513405 0.0573354  0.11759957 0.20884829]
 [0.20559203 0.22523687 0.05207789 0.1805567  0.29728667]
 [0.13119624 0.16808714 0.2634509  0.01328657 0.25685433]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [220]:
rgba_dtype = np.dtype([('R', np.int8),  # Red component
                       ('G', np.int8),  # Green component
                       ('B', np.int8),  # Blue component
                       ('A', np.int8)]) # Alpha component

print(rgba_dtype)


[('R', 'i1'), ('G', 'i1'), ('B', 'i1'), ('A', 'i1')]


# 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [223]:
arr1 = np.random.rand(5,3)
arr2 = np.random.rand(3,2)
print(arr1.dot(arr2)) #dot use multiply matrix (5*3 3*2) ,row= column =3
#print(arr1 @ arr2)

[[0.79768066 0.63276026]
 [1.03444663 0.54333313]
 [1.20777047 0.89740986]
 [0.91327268 0.46856608]
 [1.35578009 0.94532073]]
[[0.79768066 0.63276026]
 [1.03444663 0.54333313]
 [1.20777047 0.89740986]
 [0.91327268 0.46856608]
 [1.35578009 0.94532073]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [253]:
arr = np.array([1, 5, 4, 9, 3, 6, 8, 2, 7])
for i in range(len(arr)): # np use len to define count list
    if (arr[i] >= 3) and (arr[i] < 9):
        arr[i]*=-1
print(arr)

[ 1 -5 -4  9 -3 -6 -8  2 -7]


#### 28. What are the result of the following expressions? (★☆☆)
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [263]:
""""np.array(0) / np.array(0) result error nan to divide 0/0
np.array(0) // np.array(0) result 0 
np.array([np.nan]).astype(int).astype(float) convert nan to int (0)to float(0.0)"""

'"np.array(0) / np.array(0) result error nan to divide 0/0\nnp.array(0) // np.array(0) result 0 \nnp.array([np.nan]).astype(int).astype(float) convert nan to int (0)to float(0.0)'

#### 29. How to round away from zero a float array ? (★☆☆)

In [267]:
float_array = np.array([-1.5, 2.7, -3.4, 4.9])
rounded_up = np.ceil(float_array)
print("original array:", float_array)
print("rounded up:", rounded_up)

Original array: [-1.5  2.7 -3.4  4.9]
Rounded up: [-1.  3. -3.  5.]


#### 30. How to find common values between two arrays? (★☆☆)

In [270]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([3,4,5,6,7])
print(np.intersect1d(arr1, arr2))
print(type(np.intersect1d(arr1, arr2)))

[3 4 5]
<class 'numpy.ndarray'>


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)

In [265]:
np.seterr(all='ignore')

{'divide': 'ignore', 'over': 'ignore', 'under': 'ignore', 'invalid': 'ignore'}

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [254]:
import datetime
today = datetime.date.today()
yesterday = today - datetime.timedelta(days=1)
tomorrow = today + datetime.timedelta(days=1)
print("Yesterday:", yesterday)
print("Today:", today)
print("Tomorrow:", tomorrow)

Yesterday: 2024-02-19
Today: 2024-02-20
Tomorrow: 2024-02-21


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [3]:
import numpy as np
dates = np.arange('2016-07-01', '2016-08-01', dtype='datetime64[D]')
print(dates)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)*(-A/2)) in place (without copy)? (★★☆)

In [12]:
A = 5
B = 7
result1 = A + B
result2= -A/2
result = result1*result2
print("result =", result)

result = -30.0


#### 36. Extract the integer part of a random array of positive numbers using 4 different methods (★★☆)

In [45]:
arr = np.random.rand(10)*10
method_1 = np.floor(arr)
method_2 = np.trunc(arr)
method_3 = arr.astype(int)
method_4 = arr // 1
method_5 = np.ceil(arr)
print("original array:", arr)
print("integer part using np.floor:", method_1)
print("integer part using np.trunc:", method_2)
print("integer part using casting:", method_3)
print("integer part using // operator:", method_4)
print("integer part using ceil",method_5)

original array: [1.75807443 0.57043894 5.79058543 2.06127753 7.89515881 6.83765126
 2.33932734 5.16865129 7.50168026 2.24121701]
integer part using np.floor: [1. 0. 5. 2. 7. 6. 2. 5. 7. 2.]
integer part using np.trunc: [1. 0. 5. 2. 7. 6. 2. 5. 7. 2.]
integer part using casting: [1 0 5 2 7 6 2 5 7 2]
integer part using // operator: [1. 0. 5. 2. 7. 6. 2. 5. 7. 2.]
integer part using ceil [2. 1. 6. 3. 8. 7. 3. 6. 8. 3.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [29]:
rows = 5
cols = 5
array = np.zeros((rows, cols), dtype=int)
array[0, 0:5] = 0 
array[1, 0:5] = 1 
array[2, 0:5] = 2 
array[3, 0:5] = 3 
array[4,0:5] = 4   
print(array)

[[0 0 0 0 0]
 [1 1 1 1 1]
 [2 2 2 2 2]
 [3 3 3 3 3]
 [4 4 4 4 4]]


In [32]:
matrix = np.tile(np.arange(5), (5, 1))
print(matrix)


[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


In [42]:
import numpy as np

matrix = np.arange(5).reshape(1, 5).repeat(5, axis=0)

# Print the matrix
print(matrix)

[[0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]
 [0 1 2 3 4]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)

In [74]:
matrix = np.arange(11).reshape(1, 11)
matrix

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)

In [84]:
matrix = np.arange(0, 1, 0.1)
matrix

array([0. , 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8, 0.9])

#### 40. Create a random vector of size 10 and sort it (★★☆)

In [88]:
arr = np.random.rand(10)
print(np.sort(arr))

[0.25063671 0.27091932 0.46716289 0.52302084 0.57784393 0.64472243
 0.73639423 0.82127646 0.94836716 0.94837977]


#### 41. How to sum a small array faster than np.sum? (★★☆)

In [113]:
arrA = np.array((1,2,3,4,5))
arrB = np.array((1,2,3,8,5))
result=np.sum(arrA+arrB)
result

34

#### 42. Consider two random array A and B, check if they are equal (★★☆)

In [102]:
arrA = np.array((1,2,3,4,5))
arrB = np.array((1,2,3,8,5))
for i in arrA:
    for j in arrB:
        if i==j:
            
            print("equal",i,j)

equal 1 1
equal 2 2
equal 3 3
equal 5 5


In [104]:
arrA = np.array((1, 2, 3, 4, 5))
arrB = np.array((1, 2, 0, 4, 5))
if np.array_equal(arrA, arrB):
    print("Arrays are equal.")
else:
    print("Arrays are not equal.")


Arrays are not equal.


#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)

In [121]:
import math
arr=np.random.rand(10,2)
arr


array([[0.45043249, 0.90550437],
       [0.71112281, 0.2997883 ],
       [0.14530263, 0.77217513],
       [0.61304582, 0.18576813],
       [0.40140266, 0.72576411],
       [0.24387777, 0.87967107],
       [0.68031328, 0.50914726],
       [0.90552038, 0.01825632],
       [0.30913855, 0.88355053],
       [0.35123696, 0.65191475]])

In [122]:
#r=squrt(x**2+y**2)
radius=np.sqrt(arr[:, 0]**2 + arr[:, 1]**2)
#Angle=y/x
Angle=(arr[:, 1]/arr[:, 0])
polar_coordinates = np.column_stack((radius, Angle))
print(polar_coordinates)


[[1.01134939 2.01029983]
 [0.77173096 0.42157037]
 [0.78572723 5.31425446]
 [0.64057395 0.30302488]
 [0.82937184 1.80807   ]
 [0.91285133 3.60701614]
 [0.84973942 0.74840118]
 [0.90570439 0.02016113]
 [0.93607061 2.85810527]
 [0.7405135  1.85605397]]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)

In [135]:
arr = np.random.rand(10)
arr

array([0.69552176, 0.32032443, 0.93569995, 0.87780795, 0.61302424,
       0.79821997, 0.24442985, 0.10457998, 0.55924798, 0.95959933])

In [136]:
maximum=np.max(arr)
maximum

0.9595993258010368

In [137]:
arr[arr == maximum] = 0
print(arr)

[0.69552176 0.32032443 0.93569995 0.87780795 0.61302424 0.79821997
 0.24442985 0.10457998 0.55924798 0.        ]


#### 47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) (★★☆)

In [163]:
X = np.array([1, 2, 3])
Y = np.array([4, 5, 6])
#c=1/(x-y)
C = 1 / (X[:, np.newaxis] - Y)
print("Cauchy matrix C:")
print(C)


Cauchy matrix C:
[[-0.33333333 -0.25       -0.2       ]
 [-0.5        -0.33333333 -0.25      ]
 [-1.         -0.5        -0.33333333]]


#### 49. How to print all the values of an array? (★★☆)

In [145]:
arr=np.random.rand(10)
arr

array([0.30042994, 0.50227111, 0.98447052, 0.8628909 , 0.1556513 ,
       0.07609849, 0.98439538, 0.0909434 , 0.42541168, 0.4814505 ])

In [151]:
arr =np.random.rand(10)
# Use np.nditer to iterate through the array
for x in np.nditer(arr):
    print(x)

0.7905981190787306
0.055205604038003786
0.17880665413621233
0.6981525925794255
0.7253914903124186
0.380467611105906
0.3130651357497417
0.3486465362116057
0.5938827889243873
0.2262048000435236


In [158]:
arr = np.random.rand(10)
np.set_printoptions(threshold=np.inf)
print(arr)
#used print value array
#np.nditer(arr) :Use : np.nditer to iterate through the array
#np.set_printoptions :Set the printing threshold to infinity
#np.ravel :Flatten the array and print it
#np.array2string :Convert the array to a string and print it

[0.95482984 0.98533163 0.00736974 0.27067143 0.034076   0.63535585
 0.10804479 0.96197018 0.04506197 0.27660474]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)

In [160]:
x = np.arange(10)
y = 3.14
closest_index = np.argmin(np.abs(x - y))
closest_value = x[closest_index]
print(closest_value)

3


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [166]:
dtype = [('position', [('x', float), ('y', float)]),('color', [('r', int), ('g', int), ('b', int)])]
structured_array = np.array([((1.0, 2.0), (255, 0, 0)), ((3.5, 4.5), (0, 255, 0)),((6.0, 7.0), (0, 0, 255))], dtype=dtype)
print("Structured array:")
print(structured_array)


Structured array:
[((1. , 2. ), (255,   0,   0)) ((3.5, 4.5), (  0, 255,   0))
 ((6. , 7. ), (  0,   0, 255))]


#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?

In [162]:
float_array = np.array([1.1, 2.2, 3.3, 4.4, 5.5], dtype=np.float32)
float_array.astype(np.int32)
print(float_array)

[1.1 2.2 3.3 4.4 5.5]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)

In [175]:
arr = np.array([[1, 2, 3], [4, 5, 6]])
#arr=np.random.rand(5)
for index, value in np.ndenumerate(arr): # ndenumerate used both the index and value of each element
    print("index:", index, ", value:", value)


Index: (0, 0) , Value: 1
Index: (0, 1) , Value: 2
Index: (0, 2) , Value: 3
Index: (1, 0) , Value: 4
Index: (1, 1) , Value: 5
Index: (1, 2) , Value: 6


#### 58. Subtract the mean of each row of a matrix (★★☆)

In [295]:
import numpy as np
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

row_means = np.mean(matrix, axis=1, keepdims=True)

result_matrix = matrix - row_means

print("Original matrix:")
print(matrix)
print("\nSubtracting the mean of each row:")
print(result_matrix)


Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Subtracting the mean of each row:
[[-1.  0.  1.]
 [-1.  0.  1.]
 [-1.  0.  1.]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)

In [286]:
def has_null_columns(array):
    if array.size == 0:
        return False
    null_columns = np.all(array == 0, axis=1)# axis (0,1) ?
    
    return np.any(null_columns)


arr1 = np.array([[0, 9, 8],[0, 0 ,0],[4, 7, 0]])

arr2 = np.array([[0, 8, 1],[8, 6, 0],[1, 8, 0]])

print("Array 1 has null columns:", has_null_columns(arr1))
print("Array 2 has null columns:", has_null_columns(arr2))


Array 1 has null columns: True
Array 2 has null columns: False


In [270]:
import numpy as np

def has_empty_columns(array):
    empty_columns = np.all(array == 0, axis=1)
    
    return np.any(empty_columns)

arr1 = np.array([[1, 0, 3],[9, 0, 5],[0, 0, 6]])

arr2 = np.array([[1, 2, 3],[5, 0, 0],[7, 8, 9]])

print("Array 1 has empty columns:", has_empty_columns(arr1))
print("Array 2 has empty columns:", has_empty_columns(arr2))


Array 1 has empty columns: False
Array 2 has empty columns: False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [194]:
def nearest_value(array, value):
    differences = np.abs(array - value).argmin()
    nearest_value = array[differences] 
    return nearest_value

arr = np.arange(100)
given=float(input("enter value"))
nearest = nearest_value(arr, given)
print("Nearest value to", given, "in the array:", nearest)


enter value87.5
Nearest value to 87.5 in the array: 87


#### 63. Create an array class that has a name attribute (★★☆)

In [179]:
class NamedArray:
    def __init__(self, data, name=None):
        self.data = data
        self.name = name
arr = NamedArray([1, 2, 3], name='my_array')
print(arr.data)
print("Array name:", arr.name)


[1, 2, 3]
Array name: my_array


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [20]:
arr = np.array([1, 5, 4, 9, 3, 6, 8, 2, 7])
indices = np.array([0, 2, 4, 6])
for i in indices:
    arr[i]+=2
print(arr) 

[ 3  5  6  9  5  6 10  2  7]


##### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [67]:
x = np.array([5,10,15,20,25])
l = np.array([2,0,3,1,4])
f=np.zeros_like(x)
for i in range(len(l)):
        f[l[i]] += x[i]
        #f[i]=l[i]
    
print(f) 

[10 20  5 15 25]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★☆)

In [91]:

image = [[[255, 0, 0], [0, 255, 0], [255, 0, 0]],[[0, 0, 255], [255, 255, 255], [0, 0, 255]]]
image = np.array(image)
reshaped_image = image.reshape(-1, 6)
unique_colors = np.unique(reshaped_image, axis=1)
num_colors = len(unique_colors)

print("number color image:", num_colors)


number color image: 3


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [105]:
import numpy as np

array = np.random.randint(0, 100, size=(2, 2 ,2, 2))# 4d(2, 2 ,2, 2)
sum_axis = np.sum(array, axis=(-2, -1))

print("Original array:")
print(array)
print("\n last two axes:")
print(sum_axis)


Original array:
[[[[56 96]
   [90  9]]

  [[15  4]
   [49 85]]]


 [[[34 65]
   [70 95]]

  [[85 26]
   [92 30]]]]

 last two axes:
[[251 153]
 [264 233]]


#### 69. How to get the diagonal of a dot product? (★★★)

In [106]:
arr1 = np.diag([1,2,3,4])
arr2 = np.diag([1,21,9,6])
print(arr1.dot(arr2)) #dot use multiply matrix (5*3 3*2) ,row= column =3
#print(arr1 @ arr2)


[[ 1  0  0  0]
 [ 0 42  0  0]
 [ 0  0 27  0]
 [ 0  0  0 24]]


In [111]:
arr1 = np.diag([1,2,3,4])
arr2 = np.diag([1,21,9,6])
dot=np.dot(arr1,arr2)
print("dot\n",dot)
diag=np.diag(dot)
print()
print("diagonal\n",diag)

dot
 [[ 1  0  0  0]
 [ 0 42  0  0]
 [ 0  0 27  0]
 [ 0  0  0 24]]

diagonal
 [ 1 42 27 24]


#### 70. Consider the vector [1, 2, 3, 4, 5], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [170]:
original_vector = [1, 2, 3, 4, 5]

new_vector = [x for num in original_vector for x in (num, 0, 0, 0)]

# Remove the last three zeros
new_vector = new_vector[:-3]

print(new_vector)


[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5]


In [169]:
original_vector = [1, 2, 3, 4, 5]

new_vector = []

for num in original_vector:
    
    new_vector.append(num)
    new_vector.extend([0] * 3)

new_vector = new_vector[:-3]

print(new_vector)


[1, 0, 0, 0, 2, 0, 0, 0, 3, 0, 0, 0, 4, 0, 0, 0, 5]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [119]:
array = np.random.randint(0, 10, size=(5, 5 ,3))
array2 = np.random.randint(0, 10, size=(5, 5,1))
result=(array*array2)
print("orignal array\n",array)
print("orignal array2\n",array)
print("result=\n",result)



orignal array
 [[[5 2 8]
  [5 3 9]
  [3 1 6]
  [4 6 4]
  [0 8 9]]

 [[5 9 7]
  [9 4 8]
  [9 5 2]
  [2 5 8]
  [4 8 2]]

 [[8 4 5]
  [0 4 5]
  [7 4 1]
  [4 5 1]
  [4 5 8]]

 [[0 3 7]
  [0 1 9]
  [2 7 3]
  [8 8 7]
  [1 5 8]]

 [[8 2 7]
  [6 0 4]
  [1 7 5]
  [8 1 2]
  [4 1 6]]]
orignal array2
 [[[5 2 8]
  [5 3 9]
  [3 1 6]
  [4 6 4]
  [0 8 9]]

 [[5 9 7]
  [9 4 8]
  [9 5 2]
  [2 5 8]
  [4 8 2]]

 [[8 4 5]
  [0 4 5]
  [7 4 1]
  [4 5 1]
  [4 5 8]]

 [[0 3 7]
  [0 1 9]
  [2 7 3]
  [8 8 7]
  [1 5 8]]

 [[8 2 7]
  [6 0 4]
  [1 7 5]
  [8 1 2]
  [4 1 6]]]
result=
 [[[10  4 16]
  [10  6 18]
  [18  6 36]
  [32 48 32]
  [ 0 24 27]]

 [[25 45 35]
  [36 16 32]
  [27 15  6]
  [ 4 10 16]
  [ 0  0  0]]

 [[40 20 25]
  [ 0 20 25]
  [21 12  3]
  [36 45  9]
  [16 20 32]]

 [[ 0 27 63]
  [ 0  5 45]
  [ 0  0  0]
  [16 16 14]
  [ 7 35 56]]

 [[40 10 35]
  [48  0 32]
  [ 8 56 40]
  [56  7 14]
  [20  5 30]]]


#### 72. How to swap two rows of an array? (★★★)

In [174]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [7, 8, 9]])

# Swap rows 0 and 1
array[0], array[1] = array[1], array[0]

print("Array after swapping rows 0 and 1:")
print(array)


Array after swapping rows 0 and 1:
[[4 5 6]
 [4 5 6]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [176]:

boolean_value = True
negated_boolean = not boolean_value
print(negated_boolean)  


False


In [177]:

float_value = 10.5
float_value *= -1
print(float_value)  


-10.5


#### 81. Consider an array Z = [1,2,3,4,5,6,7,8,9,10,11,12,13,14], how to generate an array R = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? (★★★)

In [180]:
Z = [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14]

subarray_length = 4

R = []

for i in range(len(Z) - subarray_length + 1):
    subarray = Z[i:i+subarray_length]
    R.append(subarray)

print(R)


[[1, 2, 3, 4], [2, 3, 4, 5], [3, 4, 5, 6], [4, 5, 6, 7], [5, 6, 7, 8], [6, 7, 8, 9], [7, 8, 9, 10], [8, 9, 10, 11], [9, 10, 11, 12], [10, 11, 12, 13], [11, 12, 13, 14]]


#### 82. Compute a matrix rank (★★★)

In [178]:
import numpy as np

matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

rank = np.linalg.matrix_rank(matrix)

print("Rank of the matrix:", rank)


Rank of the matrix: 2


#### 83. How to find the most frequent value in an array?

In [186]:
from scipy.stats import mode
import numpy as np

arr = np.array([1, 1, 7, 7,7,7,8, 7, 8, 9, 9, 5, 4, 5, 4])
mode_result = mode(arr)

print("Mode of the array:", mode_result.mode)


Mode of the array: 7


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)

In [181]:
import numpy as np

array = np.random.randint(1, 10, size=(16, 16))

blocks = array.reshape(4, 4, 4, 4)

block_sum = np.sum(blocks, axis=(2, 3))

print("Block-sum (block size 4x4):")
print(block_sum)


Block-sum (block size 4x4):
[[72 79 84 68]
 [88 71 91 65]
 [89 64 88 75]
 [75 62 63 75]]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. [2,2,3]) (★★★)

In [187]:
import numpy as np

matrix = np.random.randint(0, 10, size=(10, 3))

unequal_rows = matrix[np.any(np.diff(matrix, axis=1), axis=1)]

print("Rows with unequal values:")
print(unequal_rows)


Rows with unequal values:
[[3 4 5]
 [4 1 9]
 [2 9 3]
 [1 6 4]
 [1 2 0]
 [9 4 7]
 [3 5 1]
 [3 9 2]
 [1 1 9]
 [6 0 3]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★)

In [188]:
import numpy as np

array = np.array([[1, 2, 3],
                  [4, 5, 6],
                  [1, 2, 3],
                  [7, 8, 9],
                  [4, 5, 6]])

unique_rows = np.unique(array, axis=0)

print("Unique rows:")
print(unique_rows)


Unique rows:
[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [189]:
matrix = np.random.randint(0, 10, size=(10, 3))

unequal_rows = matrix[np.all(np.diff(matrix, axis=1), axis=1)]


print("Rows with unequal values:")
print(unequal_rows)

Rows with unequal values:
[[9 3 6]
 [3 8 3]
 [9 3 1]
 [7 3 4]
 [4 3 1]
 [1 6 7]
 [9 2 8]
 [5 9 8]]
